### ISSUE TITLE
'Tag' init error

### ISSUE THREAD

**Issue by OndrejHRIC** [lukereichold/arweave-swift#2]
Xcode 12.0 (12A7209)
iOS 14.0 / 13.7
Arweave 1.0.2

If I use following code from README, I get error `Cannot find 'Tag' in scope`.
`let tag = Tag(name: "myTag", value: "myValue")`

When I try following one, I get error `Extra arguments at positions #1, #2 in call` .
`let tag = Transaction.Tag(name: "myTag", value: "myValue")`

**Comment by lukereichold** [comment]
Hi @OndrejHRIC, thanks for letting me know! This issue has been resolved in the new release, 1.0.3.
