### ISSUE TITLE
Creating wallet from existing key

### ISSUE THREAD

**Issue by jsoneaday** [lukereichold/arweave-swift#5]
I'm trying to create a Data object based on the private key of an existing wallet that I have. In javascript if I json.parse this file's contents it does create the wallet. However in swift if I use Data(JSONEncoder().encode("{key}")) it exceptions on the Wallet line.

```
let walletData = try? Data(JSONEncoder().encode("my key")
let wallet = try Wallet(jwkFileData: walletData!) // fails here
```

**Comment by lukereichold** [comment]
@jsoneaday If you're trying to create a `Data` representation of a file's contents (the JWK keyfile), you can use the steps provided in the [README](https://github.com/lukereichold/arweave-swift/blob/master/README.md):
```swift
guard let keyFileData = try? Data(contentsOf: keyFileUrl) else { return }
let wallet = Wallet(jwkFileData: keyFileData)
```

Do you mean to ask that you'd like to create a `Data` object directly from a JSON `String` (to subsequently use to create a `Wallet`)?

If so, in Swift you can convert a `String` to `Data` via the following:

```swift
let keyDataFromString = try jsonString.data(using: .utf8)
```

**Comment by jsoneaday** [comment]
Thanks I'll try that. I'm getting someone on discord saying that your library does not work on arweave v2 using either testweave or arlocal, only v1. He says he gets http 412 errors. I'll try it on my end and see.

**Comment by lukereichold** [comment]
@jsoneaday This library currently supports only v1. I've responded in the Discord channel and will open a new issue here for v2 support.

**Comment by jsoneaday** [comment]
Hey luke what is the diff in v1 vs v2. Is there a doc I can read to understand?
